name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run:  python -m unittest discover app/tests/

      - name: Generate coverage report
        run: |
          coverage run -m unittest discover app/tests/
          coverage html
          coverage report
          export COVERAGE_PERCENTAGE=$(coverage report | awk '/TOTAL/ {print $4}' | cut -d'%' -f1)

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report.html
          path: htmlcov/index.html
